### PR TITLE
Switching to argo.scripts

### PR DESCRIPTION
**Pull request by pruzanov**

### CODE REVIEW

**Review by lheisler — CHANGES_REQUESTED** [review]
the workflow should include a genome version (reference) as input and functions to set appropriate reference sequence.

**Review by lheisler — CHANGES_REQUESTED** [review]
sampleid should be passed in from the olive, this should be an input parameter.
The workflow currently determines output file names based on input file names.  This is not best practices

**Review by lheisler — COMMENTED** [review]
is the mergeVCF task still needed.  i thought in the older workflow this was a precursor to the combinevariants, but i don't think that is the case.  

if i understand correctly
mergeVCF -> concatenated vcf files
combineVCF -> 1 record per call, with information from all callers

the needed output from this is combineVCF; is mergeVCF needed?

**Review by lheisler — COMMENTED** [review]
i suggest defining modules, which are tied to the workflow version, in variables, so that if they are used for multiple tasks there is no need to update in many places

eg
gatk_module="gatk/4.2.6.1"
or
modules[gatk]="gatk/4.2.6.1"

then pass the variable to each task that needs it

**Comment by pruzanov** [comment]
> is the mergeVCF task still needed. i thought in the older workflow this was a precursor to the combinevariants, but i don't think that is the case.
> 
> if i understand correctly mergeVCF -> concatenated vcf files combineVCF -> 1 record per call, with information from all callers
> 
> the needed output from this is combineVCF; is mergeVCF needed?

That is up to the customer, who I believe is CGI. Does not hurt to have it, IMO

**Comment by pruzanov** [comment]
> the workflow should include a genome version (reference) as input and functions to set appropriate reference sequence.

We certainly have a good reason to pass reference as a parameter when we use any reference-specific resources, such as alignment indices. Here, we only use fasta/fai which come with the reference module. Do we really need to delegate module selection to the workflow if it's only the reference module? Looks to me that passing reference module from the respective olive is a cleaner solution.

**Comment by lheisler** [comment]
> > sampleid should be passed in from the olive, this should be an input parameter. The workflow currently determines output file names based on input file names. This is not best practices
> 
> No, that is not the case. **outputFileNamePrefix** is passed as a parameter, and only if it is not defined the workflow tries to construct a prefix from a file name

i thought we had decided to enforce outputFileNamePrefix as a required parameter.   If not, i think it should be best practices that this is required.  Forming names from input files has been problematic in the past.

**Comment by lheisler** [comment]
> > the workflow should include a genome version (reference) as input and functions to set appropriate reference sequence.
> 
> We certainly have a good reason to pass reference as a parameter when we use any reference-specific resources, such as alignment indices. Here, we only use fasta/fai which come with the reference module. Do we really need to delegate module selection to the workflow if it's only the reference module? Looks to me that passing reference module from the respective olive is a cleaner solution.

for uniformity we should be doing the same as other workflows.  fasta/fai will also vary if hg19 v hg38 and if we later add in new builds.

**Comment by pruzanov** [comment]
> > > the workflow should include a genome version (reference) as input and functions to set appropriate reference sequence.
> > 
> > 
> > We certainly have a good reason to pass reference as a parameter when we use any reference-specific resources, such as alignment indices. Here, we only use fasta/fai which come with the reference module. Do we really need to delegate module selection to the workflow if it's only the reference module? Looks to me that passing reference module from the respective olive is a cleaner solution.
> 
> for uniformity we should be doing the same as other workflows. fasta/fai will also vary if hg19 v hg38 and if we later add in new builds.

Not sure what what do you mean here, of course  fasta/fai will change if switch between assemblies, but baking  the reference modules into the workflow is a bit of over-engineering (since this is the only thing that changes).

**Comment by pruzanov** [comment]
> > > sampleid should be passed in from the olive, this should be an input parameter. The workflow currently determines output file names based on input file names. This is not best practices
> > 
> > 
> > No, that is not the case. **outputFileNamePrefix** is passed as a parameter, and only if it is not defined the workflow tries to construct a prefix from a file name
> 
> i thought we had decided to enforce outputFileNamePrefix as a required parameter. If not, i think it should be best practices that this is required. Forming names from input files has been problematic in the past.

**outputFileNamePrefix** is a non-optional parameter in this workflow.

**Comment by lheisler** [comment]
> 

i see this now.  using basename is just in the first task to preprocess the input vcf.  output files use the non-optional outputPrefix.  That's fine them

**Comment by lheisler** [comment]
> > 
> 
> i see this now. using basename is just in the first task to preprocess the input vcf. output files use the non-optional outputPrefix. That's fine them

following up on this:   You had indicated in an earlier comment that outputFileNamePrefix argument was non-optional, but it has a default value (""), making it optional.  And looking at the code, there is a check to determine if it has a value, and if not set then the basename of the input vcf is used.   

best practices is to have this as non optional
https://wiki.oicr.on.ca/display/GSI/WDL+Best+Practices#WDLBestPractices-Haveannon-optional%22outputFileNamePrefix%22parameterforworkflowoutputfiles

**Comment by lheisler** [comment]
> > > > sampleid should be passed in from the olive, this should be an input parameter. The workflow currently determines output file names based on input file names. This is not best practices
> > > 
> > > 
> > > No, that is not the case. **outputFileNamePrefix** is passed as a parameter, and only if it is not defined the workflow tries to construct a prefix from a file name
> > 
> > 
> > i thought we had decided to enforce outputFileNamePrefix as a required parameter. If not, i think it should be best practices that this is required. Forming names from input files has been problematic in the past.
> 
> **outputFileNamePrefix** is a non-optional parameter in this workflow.



> > > > the workflow should include a genome version (reference) as input and functions to set appropriate reference sequence.
> > > 
> > > 
> > > We certainly have a good reason to pass reference as a parameter when we use any reference-specific resources, such as alignment indices. Here, we only use fasta/fai which come with the reference module. Do we really need to delegate module selection to the workflow if it's only the reference module? Looks to me that passing reference module from the respective olive is a cleaner solution.
> > 
> > 
> > for uniformity we should be doing the same as other workflows. fasta/fai will also vary if hg19 v hg38 and if we later add in new builds.
> 
> Not sure what what do you mean here, of course fasta/fai will change if switch between assemblies, but baking the reference modules into the workflow is a bit of over-engineering (since this is the only thing that changes).

this now complies with the best practices
https://wiki.oicr.on.ca/display/GSI/WDL+Best+Practices#WDLBestPractices-ReferenceGenome

**Review by lheisler — APPROVED** [review]
all looks good now

**Pull request merged**
